### PR TITLE
Private event Project

### PR DESCRIPTION
**Pull request by pountzas**
This pull request contains the following features:
Updated Readme file
Created form for signup and sign in before creating or view an event
User should create an event after signing or signing up
User should click attend the event button to attend the event
user should cancel or ignore to attend the event
user should see the events they have created as well as events they are going to attend.

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
---------------
Hello @pountzas @mrigorir You are doing an excellent project so far :clap: :muscle: 

TO HIGHLIGHT: 

- Your repo is professional
- Your project is professional
- Well structures files
- Well use of the MVP
- I like how the views look.

However there are some changes to make to complete this project. :hammer_and_wrench: see them below :eyes: :point_down: 
------------
- [x] There is no user's show page. This show page must be displays events the user has created and events that the user is attending contains. I can see that the path for the user's page you called `Attended Events` you can call profile and add the event created by the user. 

user_events_requirement

Show action in users controller

- [x] Please change the `show` action on the user's controller to show all the events that the user has created. E.G `@created_events = current_user.events`

current_user_show_requirement

- [x] Lists events previoulsy attendented by user **using event model scope**, E:G `@past_events = current_user.attended_events.previous`
- [x] Lists upcoming events previously attended by user **using event model scope**, E:G `@upcoming_events = current_user.attended_events.upcoming`
- [x]  Please remove the methods that you are not using on the user's controller. 
- [x]  When I run `rspec` I got 15 failures. Please fix it. 

Screenshot from 2021-05-28 20-38-44
--------------
Make the required changes and send it again for another review :100: 
Reachme on SLACK if you have any questions.
@ Brian Sammit Cruz rodriguez
HAPPY CODING!!!

MB5W4D

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# CHANGES REQUIRED 🔴

Hey, @pountzas and @mrigorir, I'm happy to see almost all the changes requested by a previous reviewer being implemented, This is good news. However, there are few issues to fix before we can move.

- [ ] I'm getting an error when I try to log out, See this image below.
logout

- [ ] I'm getting this error when I click the attend event button,
routes

- [ ] I can't test because I'm getting the error in the image below
rspec

<hr>

**Please make all the changes and submit another PR for a review**
In case you have a question, reach me on slack as Elisha kyakopo

Happy coding💪🎉✔

**Comment by mrigorir** [comment]
Appreciated TSEs's, PLEASE NOTE: 

For further revisions, before starting the server run the following commands:

- Rub yarn add jquery popper.js bootstrap

- Run db:migrate so you can have the representations of tables in your project.

For testing:

- Run rake db:migrate RAILS_ENV=test so you can have the representations of test tables in your project.

- run rspec to run the test cases.

This info is indicated at the end of the REDADME file.

**Comment by pountzas** [comment]
Those problems do not exist. Did you run all the commands mentioned in the Readme.md?? We even cloned the repo and running all commands and the project works even rspec i don't know where you got this.

**Review by mke2111 — APPROVED** [review]
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coders, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The tests run just fine
    2. The instructions to run the app were clear
    

### **_Room for Improvement_** 🤪 

    1. You might want to add more tests for your app. Consider integration tests the most.
    2. Remove all pieces of commented-out code from all your files.

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Pull request merged**
